# Generated by Django 5.0.3 on 2024-04-08 15:07

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='', editable=False, populate_from='title', unique=True, verbose_name='URL'),
        ),
    ]
