# Generated by Django 5.0.3 on 2024-04-08 15:48

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_publication_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, editable=False, populate_from=('title',), verbose_name='Slug'),
        ),
    ]
