# Generated by Django 5.0.3 on 2024-04-11 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_publication_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='is_paid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='app.subscription', verbose_name='Подписка'),
        ),
    ]
