# Generated by Django 5.0.3 on 2024-04-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_publication_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='paid_publication',
            field=models.ManyToManyField(blank=True, to='app.publication', verbose_name='Оплаченные публикации'),
        ),
    ]
