# Generated by Django 5.0.3 on 2024-04-15 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_subscription_paid_publication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-date'], 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
